subscription newMove {
  newMove {
    i
    j
    game {
      currentTurn {
        playerType
      }
    }
    player {
      playerType
    }
  }
}

subscription gameEnds {
  gameEnds {
    playerType
    moves {
      id
    }
  }
}
